version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-dependencies-{{ checksum "batmobile/yarn.lock" }}
            - v1-yarn-dependencies-
      - run:
          name: Install Dependencies
          command: |
            cd batmobile
            yarn install
      - save_cache:
          paths:
            - batmobile/node_modules
          key: v1-yarn-dependencies-{{ checksum "batmobile/yarn.lock" }}
      - run:
          name: Run Tests
          command: |
            cd batmobile
            yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build